source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem "mysql"
gem 'curb', :git => 'https://github.com/taf2/curb.git'
gem "json"
gem "ruby-debug"
gem "SystemTimer"

gem "hiredis"
gem "redis", ">= 2.2.0", :require => ["redis/connection/hiredis", "redis"]
gem "resque"
gem "resque-scheduler",
  :git => "git://github.com/chetan/resque-scheduler.git",
  :require => ["resque_scheduler"]
gem "redis-lock"

group :development do
    gem "cucumber"
    gem "cucumber-rails"
    gem "rcov"
    gem "rcov_rails"
end
