source 'http://rubygems.org'

gem 'rails', '3.0.7'

gem "mysql"
gem "curb"
gem "json"
gem "ruby-debug"

group :development do
    gem "cucumber"
    gem "cucumber-rails"
    gem "rcov"
    gem "rcov_rails"
end
