source 'http://rubygems.org'

gem 'rails', '3.2.1'

gem 'devops_common', :git => "https://github.com/chetan/devops_common.git"

gem "mysql"
gem "curb"
gem "json"
gem "ruby-debug", :platforms => :mri_18
gem "ruby-debug19", :platforms => :mri_19
gem "SystemTimer", :platforms => :mri_18
gem "git"

gem 'haml'
gem 'simple_form'

# scheduler module
gem "hiredis"
gem "redis", ">= 2.2.0", :require => ["redis/connection/hiredis", "redis"]
gem "resque"
gem "resque-scheduler",
  :git => "git://github.com/chetan/resque-scheduler.git",
  :require => ["resque_scheduler"]
gem "redis-lock"

group :assets do
    gem 'less'
    gem 'less-rails'
end

group :development do
    gem "lorem_ipsum", :git => 'git://github.com/chetan/lorem_ipsum.git'
    gem 'newrelic_rpm'
    gem "awesome_print"

    gem "cucumber"
    gem "cucumber-rails"
    gem "rcov", :platforms => :mri_18
    gem "rcov_rails", :platforms => :mri_18
    gem "simplecov", :platforms => :mri_19
end
