# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bixby_agent"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chetan Sarva"]
  s.date = "2012-06-12"
  s.description = "Bixby Agent"
  s.email = "chetan@pixelcop.net"
  s.executables = ["agent", "agent.rb"]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "VERSION",
    "bin/agent",
    "bin/agent.rb",
    "devops_agent.gemspec",
    "lib/bixby_agent.rb",
    "lib/bixby_agent/agent.rb",
    "lib/bixby_agent/agent/config.rb",
    "lib/bixby_agent/agent/crypto.rb",
    "lib/bixby_agent/agent/handshake.rb",
    "lib/bixby_agent/agent/remote_exec.rb",
    "lib/bixby_agent/api/modules/inventory.rb",
    "lib/bixby_agent/api/modules/provisioning.rb",
    "lib/bixby_agent/app.rb",
    "lib/bixby_agent/bootstrap.rb",
    "lib/bixby_agent/cli.rb",
    "lib/bixby_agent/config_exception.rb",
    "lib/bixby_agent/model/bundle_command.rb",
    "lib/bixby_agent/model/bundle_util.rb",
    "lib/bixby_agent/server.rb",
    "repo/system/provisioning/bin/get_bundle.rb",
    "repo/system/provisioning/manifest.json",
    "tasks/cucumber.rake",
    "test/helper.rb",
    "test/support/root_dir/devops.yml",
    "test/support/root_dir/id_rsa",
    "test/support/root_dir/id_rsa.pub",
    "test/support/test_bundle/bin/cat",
    "test/support/test_bundle/bin/echo",
    "test/support/test_bundle/digest",
    "test/support/test_bundle/manifest.json",
    "test/test_agent.rb",
    "test/test_agent_exec.rb",
    "test/test_app.rb",
    "test/test_bundle_command.rb",
    "test/test_devops_common.rb",
    "test/test_get_bundle.rb",
    "test/test_provisioning.rb",
    "test_guard.rb"
  ]
  s.homepage = "http://github.com/chetan/devops"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Bixby Agent"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

