source 'http://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'curb'
gem 'ohai'
gem 'mixlib-cli'
gem 'uuidtools'
gem 'ezcrypto'

group :development, :test do
    gem 'cucumber'
    gem 'minitest'
    gem 'rcov'
end
