source 'http://rubygems.org'

gem 'devops_common', :git => "https://github.com/chetan/devops_common.git"

gem 'sinatra'
gem 'thin'
gem 'multi_json'
gem 'oj'
gem 'curb'
gem 'facter'
gem 'mixlib-cli'
gem 'uuidtools'
gem 'ezcrypto'
gem 'systemu'
gem 'logging'

group :development, :test do

    # packaging
    gem 'jeweler', '~> 1.8.3'
    gem 'yard', '~> 0.7'

    # debugging
    gem 'pry'
    gem 'awesome_print'
    gem 'guard'
    gem 'colorize'
    gem 'growl'
    gem 'hirb'

    # test frameworks
    # gem 'cucumber'
    # gem 'aruba', '0.4.7'
    # gem 'rspec'
    gem "bahia"
    gem 'webmock', :git => 'https://github.com/bblimke/webmock.git'
    gem 'mocha'
    gem "minitest"
    gem "turn"

    # coverage
    gem "simplecov",:platforms => :mri_19
    gem "rcov", :platforms => :mri_18
end
