source 'http://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'curb'
gem 'facter'
gem 'mixlib-cli'
gem 'uuidtools'
gem 'ezcrypto'
gem 'systemu'

group :development, :test do
    gem 'cucumber'
    gem 'aruba'
    gem 'minitest'
    gem 'rcov'
    gem 'rspec'
end
